### ISSUE TITLE
Error: Not Found 

### ISSUE THREAD

**Issue by CJBrew** [coapp/coapp.org#42]
Trying to get help with CoApp from the website, and I'm having some problems....

I don't *think* this is a proxy issue at my end but I could be wrong.  Neither Chrome nor IE 11 are working.

Screenshot attached
![errornotfound](https://cloud.githubusercontent.com/assets/992038/9335655/2ba0c740-45cd-11e5-9199-35a0c922ee1b.png)

**Comment by mariusheise** [comment]
Been having the same problem about a week. On Firefox, IE, Chrome...

**Comment by virmitio** [comment]
This is being investigated.

**Comment by Thieum** [comment]
:+1

**Comment by virmitio** [comment]
This issue should be resolved.  It was the result of failing calls to a no-longer-existent web api during page generation.

**Comment by unholytony** [comment]
Sorry , I'm not sure if I should be commenting here or opening a new issue.

This doesn't appear to be fixed for me as of Sept. 7th 2015.
This URL: http://coapp.org/tutorials/installation.html
Looks like this:

![image](https://cloud.githubusercontent.com/assets/5261390/9719149/aea2059e-5579-11e5-9a67-4eefe326b568.png)
